import React from 'react'
import Header from '../header/Header'

export default function About() {
    return (
        <div><Header/>
            <h2>About Page</h2>
            <p>he oceanic whitetip shark is a large requiem shark inhabiting tropical and warm temperate seas. It has a stocky body with long, white-tipped, rounded fins. The species is typically solitary but can congregate around food concentrations. It is found worldwide between 45°N and 43°S latitudes in deep, open oceans. Bony fish and cephalopods are the main components of its diet. Females give live birth after a gestation period of nine to twelve months. Though slow-moving, it is opportunistic, aggressive, and reputed to be dangerous to shipwreck survivors. The shark was once extremely common and widely distributed; up to the 16th century, mariners noted that this species was the most common ship-following shark. The species has now been listed as critically endangered, and recent studies show steeply declining populations worldwide as the sharks are harvested for their fins and meat, like many other shark species.he oceanic whitetip shark is a large requiem shark inhabiting tropical and warm temperate seas. It has a stocky body with long, white-tipped, rounded fins. The species is typically solitary but can congregate around food concentrations. It is found worldwide between 45°N and 43°S latitudes in deep, open oceans. Bony fish and cephalopods are the main components of its diet. Females give live birth after a gestation period of nine to twelve months. Though slow-moving, it is opportunistic, aggressive, and reputed to be dangerous to shipwreck survivors. The shark was once extremely common and widely distributed; up to the 16th century, mariners noted that this species was the most common ship-following shark. The species has now been listed as critically endangered, and recent studies show steeply declining populations worldwide as the sharks are harvested for their fins and meat, like many other shark species. he oceanic whitetip shark is a large requiem shark inhabiting tropical and warm temperate seas. It has a stocky body with long, white-tipped, rounded fins. The species is typically solitary but can congregate around food concentrations. It is found worldwide between 45°N and 43°S latitudes in deep, open oceans. Bony fish and cephalopods are the main components of its diet. Females give live birth after a gestation period of nine to twelve months. Though slow-moving, it is opportunistic, aggressive, and reputed to be dangerous to shipwreck survivors. The shark was once extremely common and widely distributed; up to the 16th century, mariners noted that this species was the most common ship-following shark. The species has now been listed as critically endangered, and recent studies show steeply declining populations worldwide as the sharks are harvested for their fins and meat, like many other shark species. (Full article...)</p>
        </div>
    )
}
